# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)


User.delete_all
us01 = User.create!(email: "aku@gmail.com", password: "password")
us02 = User.create!(email: "richill@gmail.com", password: "password")


# level_01
CategoryProducttype.delete_all
cpt01 = CategoryProducttype.create!(name: 'men', code_name: 'p_cat_men', user_id: us01.id)
cpt02 = CategoryProducttype.create!(name: 'women', code_name: 'p_cat_women', user_id: us01.id)
cpt03 = CategoryProducttype.create!(name: 'kids (boys)', code_name: 'p_cat_kids_boys', user_id: us01.id)
cpt04 = CategoryProducttype.create!(name: 'kids (girls)', code_name: 'p_cat_kids_girls', user_id: us01.id)
cpt05 = CategoryProducttype.create!(name: 'product', code_name: 'p_cat_product', user_id: us01.id)


# level_02
CategoryProductitemtype.delete_all
cpit01 = CategoryProductitemtype.create!(name: 'accessories', code_name: 'p_type_accessories', user_id: us01.id)
cpit02 = CategoryProductitemtype.create!(name: 'coats & jackets', code_name: 'p_type_coats',user_id: us01.id)
cpit03 = CategoryProductitemtype.create!(name: 'clothing', code_name: 'p_type_clothing',user_id: us01.id)
cpit04 = CategoryProductitemtype.create!(name: 'footwear', code_name: 'p_type_footwear',user_id: us01.id)
cpit05 = CategoryProductitemtype.create!(name: 'gifts', code_name: 'p_type_gifts',user_id: us01.id)
cpit06 = CategoryProductitemtype.create!(name: 'skincare', code_name: 'p_type_skincare',user_id: us01.id)
cpit07 = CategoryProductitemtype.create!(name: 'home furnishing', code_name: 'p_type_home_furnishing',user_id: us01.id)
cpit08 = CategoryProductitemtype.create!(name: 'furniture', code_name: 'p_type_furniture',user_id: us01.id)
cpit09 = CategoryProductitemtype.create!(name: 'home & gardening', code_name: 'p_type_home_gardening',user_id: us01.id)
cpit10 = CategoryProductitemtype.create!(name: 'mother care', code_name: 'p_type_mother_care',user_id: us01.id)
cpit11 = CategoryProductitemtype.create!(name: 'phones, cellphones & telecommunications', code_name: 'p_type_phones_telecom',user_id: us01.id)
cpit12 = CategoryProductitemtype.create!(name: 'computer & office', code_name: 'p_type_comp_office',user_id: us01.id)
cpit13 = CategoryProductitemtype.create!(name: 'education & office supplies', code_name: 'p_type_education',user_id: us01.id)
cpit14 = CategoryProductitemtype.create!(name: 'security & protection', code_name: 'p_type_security',user_id: us01.id)
cpit15 = CategoryProductitemtype.create!(name: 'consumer electronics', code_name: 'p_type_consumer_electronics',user_id: us01.id)
cpit16 = CategoryProductitemtype.create!(name: 'pet supplies', code_name: 'p_type_pet',user_id: us01.id)
cpit17 = CategoryProductitemtype.create!(name: 'toys & hobbies', code_name: 'p_type_toys',user_id: us01.id)
cpit18 = CategoryProductitemtype.create!(name: 'musical instruments', code_name: 'p_type_musical',user_id: us01.id)
cpit19 = CategoryProductitemtype.create!(name: 'hair extensions & wigs', code_name: 'p_type_hair',user_id: us01.id)
cpit20 = CategoryProductitemtype.create!(name: 'salon equipments', code_name: 'p_type_salon',user_id: us01.id)
cpit21 = CategoryProductitemtype.create!(name: 'automobiles & motorcycles', code_name: 'p_type_auto',user_id: us01.id)
cpit22 = CategoryProductitemtype.create!(name: 'sport equipments', code_name: 'p_type_sport_equip',user_id: us01.id)
cpit23 = CategoryProductitemtype.create!(name: 'construction & real estate', code_name: 'p_type_construction_estate',user_id: us01.id)


# level_03
CategoryProductsubtype.delete_all
# accessories
cps01 = CategoryProductsubtype.create!(name: 'belts', code_name: 'p_subtype_belts', category_productitemtype_id: cpit01.id, user_id: us01.id)
cps02 = CategoryProductsubtype.create!(name: 'gloves', code_name: 'p_subtype_gloves', category_productitemtype_id: cpit01.id, user_id: us01.id)
cps03 = CategoryProductsubtype.create!(name: 'hats & caps', code_name: 'p_subtype_hats', category_productitemtype_id: cpit01.id, user_id: us01.id)
cps04 = CategoryProductsubtype.create!(name: 'hair accessories', code_name: 'p_subtype_hair_acc', category_productitemtype_id: cpit01.id, user_id: us01.id)
cps05 = CategoryProductsubtype.create!(name: 'handbags & purses', code_name: 'p_subtype_handbags', category_productitemtype_id: cpit01.id, user_id: us01.id)
cps06 = CategoryProductsubtype.create!(name: 'jewellery', code_name: 'p_subtype_jewellery', category_productitemtype_id: cpit01.id, user_id: us01.id)
cps07 = CategoryProductsubtype.create!(name: 'sunglasses', code_name: 'p_subtype_sunglasses', category_productitemtype_id: cpit01.id, user_id: us01.id)
cps08 = CategoryProductsubtype.create!(name: 'scarves', code_name: 'p_subtype_scarves', category_productitemtype_id: cpit01.id, user_id: us01.id)
cps09 = CategoryProductsubtype.create!(name: 'umbrellas', code_name: 'p_subtype_umbrellas', category_productitemtype_id: cpit01.id, user_id: us01.id)
cps10 = CategoryProductsubtype.create!(name: 'watches', code_name: 'p_subtype_watches', category_productitemtype_id: cpit01.id, user_id: us01.id)
cps11 = CategoryProductsubtype.create!(name: 'handkerchiefs', code_name: 'p_subtype_handkerchiefs', category_productitemtype_id: cpit01.id, user_id: us01.id)
cps12 = CategoryProductsubtype.create!(name: 'ties & bow ties', code_name: 'p_subtype_ties_bows', category_productitemtype_id: cpit01.id, user_id: us01.id)
# coats & jackets
cps13 = CategoryProductsubtype.create!(name: 'jackets', code_name: 'p_subtype_jackets', category_productitemtype_id: cpit02.id, user_id: us01.id)
cps14 = CategoryProductsubtype.create!(name: 'coats', code_name: 'p_subtype_coats', category_productitemtype_id: cpit02.id, user_id: us01.id)
cps15 = CategoryProductsubtype.create!(name: 'capes', code_name: 'p_subtype_capes', category_productitemtype_id: cpit02.id, user_id: us01.id)
cps16 = CategoryProductsubtype.create!(name: 'gilet', code_name: 'p_subtype_gilet', category_productitemtype_id: cpit02.id, user_id: us01.id)
# clothing
cps17 = CategoryProductsubtype.create!(name: 'dresses', code_name: 'p_subtype_dresses', category_productitemtype_id: cpit03.id, user_id: us01.id)
cps18 = CategoryProductsubtype.create!(name: 'tops & tees', code_name: 'p_subtype_tops_tees', category_productitemtype_id: cpit03.id, user_id: us01.id)
cps19 = CategoryProductsubtype.create!(name: 'bottoms & trousers', code_name: 'p_subtype_bottoms_trousers', category_productitemtype_id: cpit03.id, user_id: us01.id)
cps20 = CategoryProductsubtype.create!(name: 'jeans', code_name: 'p_subtype_jeans', category_productitemtype_id: cpit03.id, user_id: us01.id)
cps21 = CategoryProductsubtype.create!(name: 'skirts', code_name: 'p_subtype_skirts', category_productitemtype_id: cpit03.id, user_id: us01.id)
cps22 = CategoryProductsubtype.create!(name: 'jumpsuits & bodysuits', code_name: 'p_subtype_jumpsuits', category_productitemtype_id: cpit03.id, user_id: us01.id)
cps23 = CategoryProductsubtype.create!(name: 'sweaters & jumpers', code_name: 'p_subtype_sweaters_jumpers', category_productitemtype_id: cpit03.id, user_id: us01.id)
cps24 = CategoryProductsubtype.create!(name: 'suits & tailoring', code_name: 'p_subtype_suits_tailoring', category_productitemtype_id: cpit03.id, user_id: us01.id)
cps25 = CategoryProductsubtype.create!(name: 'nightwear & underwear', code_name: 'p_subtype_nightwear', category_productitemtype_id: cpit03.id, user_id: us01.id)
cps26 = CategoryProductsubtype.create!(name: 'clothing uniforms', code_name: 'p_subtype_clothing_uniforms', category_productitemtype_id: cpit03.id, user_id: us01.id)
cps27 = CategoryProductsubtype.create!(name: 'sportswear', code_name: 'p_subtype_sportswear', category_productitemtype_id: cpit03.id, user_id: us01.id)
cps28 = CategoryProductsubtype.create!(name: 'clothing accessories', code_name: 'p_subtype_clothing_accessories', category_productitemtype_id: cpit03.id, user_id: us01.id)
# footwear
cps29 = CategoryProductsubtype.create!(name: 'boots', code_name: 'p_subtype_boots', category_productitemtype_id: cpit04.id, user_id: us01.id)
cps30 = CategoryProductsubtype.create!(name: 'flats', code_name: 'p_subtype_flats', category_productitemtype_id: cpit04.id, user_id: us01.id)
cps31 = CategoryProductsubtype.create!(name: 'shoes', code_name: 'p_subtype_shoes', category_productitemtype_id: cpit04.id, user_id: us01.id)
cps32 = CategoryProductsubtype.create!(name: 'shoes accessories', code_name: 'p_subtype_shoes_accessories', category_productitemtype_id: cpit04.id, user_id: us01.id)
# gifts
cps33 = CategoryProductsubtype.create!(name: 'product items', code_name: 'p_subtype_prod_items', category_productitemtype_id: cpit05.id, user_id: us01.id)
cps34 = CategoryProductsubtype.create!(name: 'food items', code_name: 'p_subtype_food_items', category_productitemtype_id: cpit05.id, user_id: us01.id)
cps35 = CategoryProductsubtype.create!(name: 'alcohol items', code_name: 'p_subtype_alcohol_items', category_productitemtype_id: cpit05.id, user_id: us01.id)
cps36 = CategoryProductsubtype.create!(name: 'toys', code_name: 'p_subtype_toys', category_productitemtype_id: cpit05.id, user_id: us01.id)
# skincare
cps37 = CategoryProductsubtype.create!(name: 'skin & body care', code_name: 'p_subtype_skin_body', category_productitemtype_id: cpit06.id, user_id: us01.id)
cps38 = CategoryProductsubtype.create!(name: 'oral hygiene', code_name: 'p_subtype_oral', category_productitemtype_id: cpit06.id, user_id: us01.id)
cps39 = CategoryProductsubtype.create!(name: 'tattoo & body art', code_name: 'p_subtype_tattoo', category_productitemtype_id: cpit06.id, user_id: us01.id)
cps40 = CategoryProductsubtype.create!(name: 'hair care', code_name: 'p_subtype_hair_care', category_productitemtype_id: cpit06.id, user_id: us01.id)
cps41 = CategoryProductsubtype.create!(name: 'make-up', code_name: 'p_subtype_make_up', category_productitemtype_id: cpit06.id, user_id: us01.id)
cps42 = CategoryProductsubtype.create!(name: 'bath & body', code_name: 'p_subtype_bath', category_productitemtype_id: cpit06.id, user_id: us01.id)
cps43 = CategoryProductsubtype.create!(name: 'nails', code_name: 'p_subtype_nails', category_productitemtype_id: cpit06.id, user_id: us01.id)
cps44 = CategoryProductsubtype.create!(name: 'perfume & colognes', code_name: 'p_subtype_perfume_colognes', category_productitemtype_id: cpit06.id, user_id: us01.id)
cps45 = CategoryProductsubtype.create!(name: 'sun care', code_name: 'p_subtype_sun_care', category_productitemtype_id: cpit06.id, user_id: us01.id)
cps46 = CategoryProductsubtype.create!(name: 'personal care appliances & equipments', code_name: 'p_subtype_personal_care', category_productitemtype_id: cpit06.id, user_id: us01.id)
# home furnishing
cps47 = CategoryProductsubtype.create!(name: 'home bedding', code_name: 'p_subtype_home_bedding', category_productitemtype_id: cpit07.id, user_id: us01.id)
cps48 = CategoryProductsubtype.create!(name: 'bathroom', code_name: 'p_subtype_bathroom', category_productitemtype_id: cpit07.id, user_id: us01.id)
cps49 = CategoryProductsubtype.create!(name: 'cooking & dining', code_name: 'p_subtype_cooking', category_productitemtype_id: cpit07.id, user_id: us01.id)
cps50 = CategoryProductsubtype.create!(name: 'home decor', code_name: 'p_subtype_home_decor', category_productitemtype_id: cpit07.id, user_id: us01.id)
cps51 = CategoryProductsubtype.create!(name: 'home storage & organisation', code_name: 'p_subtype_home_storage', category_productitemtype_id: cpit07.id, user_id: us01.id)
cps52 = CategoryProductsubtype.create!(name: 'household cleaning', code_name: 'p_subtype_house_cleaning', category_productitemtype_id: cpit07.id, user_id: us01.id)
cps53 = CategoryProductsubtype.create!(name: 'home accessories', code_name: 'p_subtype_home_accessories', category_productitemtype_id: cpit07.id, user_id: us01.id)
cps54 = CategoryProductsubtype.create!(name: 'lights & lighting', code_name: 'p_subtype_lights', category_productitemtype_id: cpit07.id, user_id: us01.id)
cps55 = CategoryProductsubtype.create!(name: 'kitchen appliances', code_name: 'p_subtype_kitchen', category_productitemtype_id: cpit07.id, user_id: us01.id)
cps56 = CategoryProductsubtype.create!(name: 'household appliances', code_name: 'p_subtype_household_appliance', category_productitemtype_id: cpit07.id, user_id: us01.id)
cps57 = CategoryProductsubtype.create!(name: 'fabrics & textiles', code_name: 'p_subtype_fabrics_textiles', category_productitemtype_id: cpit07.id, user_id: us01.id)
cps58 = CategoryProductsubtype.create!(name: 'home flooring', code_name: 'p_subtype_home_flooring', category_productitemtype_id: cpit07.id, user_id: us01.id)
# furniture
cps59 = CategoryProductsubtype.create!(name: 'living room furniture', code_name: 'p_subtype_living_room_furniture', category_productitemtype_id: cpit08.id, user_id: us01.id)
cps60 = CategoryProductsubtype.create!(name: 'bedroom furniture', code_name: 'p_subtype_bedroom_furniture', category_productitemtype_id: cpit08.id, user_id: us01.id)
cps61 = CategoryProductsubtype.create!(name: 'sofas', code_name: 'p_subtype_sofas', category_productitemtype_id: cpit08.id, user_id: us01.id)
cps62 = CategoryProductsubtype.create!(name: 'armchairs', code_name: 'p_subtype_armchairs', category_productitemtype_id: cpit08.id, user_id: us01.id)
cps63 = CategoryProductsubtype.create!(name: 'dining tables', code_name: 'p_subtype_dining_tables', category_productitemtype_id: cpit08.id, user_id: us01.id)
cps64 = CategoryProductsubtype.create!(name: 'dining chairs', code_name: 'p_subtype_dining_chairs', category_productitemtype_id: cpit08.id, user_id: us01.id)
cps65 = CategoryProductsubtype.create!(name: 'sideboards', code_name: 'p_subtype_sideboards', category_productitemtype_id: cpit08.id, user_id: us01.id)
cps66 = CategoryProductsubtype.create!(name: 'beds', code_name: 'p_subtype_beds', category_productitemtype_id: cpit08.id, user_id: us01.id)
cps67 = CategoryProductsubtype.create!(name: 'nursery', code_name: 'p_subtype_nursery', category_productitemtype_id: cpit08.id, user_id: us01.id)
cps68 = CategoryProductsubtype.create!(name: 'garden furniture', code_name: 'p_subtype_garden_furniture', category_productitemtype_id: cpit08.id, user_id: us01.id)
cps69 = CategoryProductsubtype.create!(name: 'office furniture', code_name: 'p_subtype_office_furniture', category_productitemtype_id: cpit08.id, user_id: us01.id)
# home & gardening
cps70 = CategoryProductsubtype.create!(name: 'fertiliser', code_name: 'p_subtype_fertiliser', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps71 = CategoryProductsubtype.create!(name: 'beekeeping supplies', code_name: 'p_subtype_beekeeping', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps72 = CategoryProductsubtype.create!(name: 'plant support & care', code_name: 'p_subtype_plant_care', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps73 = CategoryProductsubtype.create!(name: 'seed disseminators', code_name: 'p_subtype_seed_disseminator', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps74 = CategoryProductsubtype.create!(name: 'indoor gardening & hydroponics', code_name: 'p_subtype_indoor_gardening', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps75 = CategoryProductsubtype.create!(name: 'outdoor hot tubs & accessories', code_name: 'p_subtype_outdoor_hot_accessories', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps76 = CategoryProductsubtype.create!(name: 'pest control', code_name: 'p_subtype_pest_control', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps77 = CategoryProductsubtype.create!(name: 'yard & garden decor', code_name: 'p_subtype_garden_decor', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps78 = CategoryProductsubtype.create!(name: 'garden carts', code_name: 'p_subtype_garden_cart', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps79 = CategoryProductsubtype.create!(name: 'pond liners', code_name: 'p_subtype_pond_liner', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps80 = CategoryProductsubtype.create!(name: 'watering & irrigation', code_name: 'p_subtype_watering', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps81 = CategoryProductsubtype.create!(name: 'shade', code_name: 'p_subtype_shade', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps82 = CategoryProductsubtype.create!(name: 'garden pots & planters', code_name: 'p_subtype_garden_pots', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps83 = CategoryProductsubtype.create!(name: 'BBQ', code_name: 'p_subtype_bbq', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps84 = CategoryProductsubtype.create!(name: 'garden buildings', code_name: 'p_subtype_garden_buildings', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps85 = CategoryProductsubtype.create!(name: 'garden tools', code_name: 'p_subtype_garden_tools', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps86 = CategoryProductsubtype.create!(name: 'mailboxes', code_name: 'p_subtype_mailboxes', category_productitemtype_id: cpit09.id, user_id: us01.id)
cps87 = CategoryProductsubtype.create!(name: 'outdoor heaters', code_name: 'p_subtype_outdoor_heaters', category_productitemtype_id: cpit09.id, user_id: us01.id)
# mother care
cps88 = CategoryProductsubtype.create!(name: 'baby stroller & accessories', code_name: 'p_subtype_baby_stroller', category_productitemtype_id: cpit10.id, user_id: us01.id)
cps89 = CategoryProductsubtype.create!(name: 'potty training', code_name: 'p_subtype_potty_training', category_productitemtype_id: cpit10.id, user_id: us01.id)
cps90 = CategoryProductsubtype.create!(name: 'car seats & accessories', code_name: 'p_subtype_car_seats_accessories', category_productitemtype_id: cpit10.id, user_id: us01.id)
cps91 = CategoryProductsubtype.create!(name: 'pregnancy & maternity', code_name: 'p_subtype_pregnancy', category_productitemtype_id: cpit10.id, user_id: us01.id)
cps92 = CategoryProductsubtype.create!(name: 'nappy bedding & changing', code_name: 'p_subtype_nappy_bedding_changing', category_productitemtype_id: cpit10.id, user_id: us01.id)
cps93 = CategoryProductsubtype.create!(name: 'activity & gear', code_name: 'p_subtype_activity_gear', category_productitemtype_id: cpit10.id, user_id: us01.id)
cps94 = CategoryProductsubtype.create!(name: 'feeding', code_name: 'p_subtype_feeding', category_productitemtype_id: cpit10.id, user_id: us01.id)
cps95 = CategoryProductsubtype.create!(name: 'safety equipment', code_name: 'p_subtype_safety_equip', category_productitemtype_id: cpit10.id, user_id: us01.id)
cps96 = CategoryProductsubtype.create!(name: 'baby care', code_name: 'p_subtype_baby_care', category_productitemtype_id: cpit10.id, user_id: us01.id)
cps97 = CategoryProductsubtype.create!(name: 'kids toys', code_name: 'p_subtype_kids_toys', category_productitemtype_id: cpit10.id, user_id: us01.id)
# phones, cellphones & telecommunications
cps98 = CategoryProductsubtype.create!(name: 'mobile phones', code_name: 'p_subtype_mobile', category_productitemtype_id: cpit11.id, user_id: us01.id)
cps99 = CategoryProductsubtype.create!(name: 'mobile phone parts', code_name: 'p_subtype_mobile_parts', category_productitemtype_id: cpit11.id, user_id: us01.id)
cps100 = CategoryProductsubtype.create!(name: 'communication equipments', code_name: 'p_subtype_com_equipment', category_productitemtype_id: cpit11.id, user_id: us01.id)
cps101 = CategoryProductsubtype.create!(name: 'walkie talkie', code_name: 'p_subtype_walkie', category_productitemtype_id: cpit11.id, user_id: us01.id)
# computer & office
cps102 = CategoryProductsubtype.create!(name: 'storage devices', code_name: 'p_subtype_storage_devices', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps103 = CategoryProductsubtype.create!(name: 'laptops', code_name: 'p_subtype_laptops', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps104 = CategoryProductsubtype.create!(name: 'servers', code_name: 'p_subtype_servers', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps105 = CategoryProductsubtype.create!(name: 'demo board & accessories', code_name: 'p_subtype_demo_board_accessories', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps106 = CategoryProductsubtype.create!(name: 'desktops', code_name: 'p_subtype_desktops', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps107 = CategoryProductsubtype.create!(name: 'tablets', code_name: 'p_subtype_tablets', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps108 = CategoryProductsubtype.create!(name: 'computer cables & connectors', code_name: 'p_subtype_computer_cables', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps109 = CategoryProductsubtype.create!(name: 'office software', code_name: 'p_subtype_office_software', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps110 = CategoryProductsubtype.create!(name: 'mini PC', code_name: 'p_subtype_mini_pc', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps111 = CategoryProductsubtype.create!(name: 'computer networking', code_name: 'p_subtype_computer_networking', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps112 = CategoryProductsubtype.create!(name: 'computer peripherals & components', code_name: 'p_subtype_computer_peripherals', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps113 = CategoryProductsubtype.create!(name: 'device cleaners', code_name: 'p_subtype_device_cleaners', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps114 = CategoryProductsubtype.create!(name: 'office electronics', code_name: 'p_subtype_office_electronic', category_productitemtype_id: cpit12.id, user_id: us01.id)
cps115 = CategoryProductsubtype.create!(name: 'industrial computers & accessories', code_name: 'p_subtype_industrial_computers_accessories', category_productitemtype_id: cpit12.id, user_id: us01.id)
# education & office supplies
cps116 = CategoryProductsubtype.create!(name: 'pens', code_name: 'p_subtype_pens', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps117 = CategoryProductsubtype.create!(name: 'pencils', code_name: 'p_subtype_pencils', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps118 = CategoryProductsubtype.create!(name: 'markers & highlighters', code_name: 'p_subtype_markers_highlighters ', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps119 = CategoryProductsubtype.create!(name: 'correction supplies', code_name: 'p_subtype_correction_supplies', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps120 = CategoryProductsubtype.create!(name: 'school & educational supplies', code_name: 'p_subtype_school_educational', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps121 = CategoryProductsubtype.create!(name: 'notebooks & writing pads', code_name: 'p_subtype_notebook', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps122 = CategoryProductsubtype.create!(name: 'labels, indexes , stickers & stamps', code_name: 'p_subtype_labels, ', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps123 = CategoryProductsubtype.create!(name: 'tapes, adhesive & fasteners', code_name: 'p_subtype_tapes_adhesive', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps124 = CategoryProductsubtype.create!(name: 'books & magazines', code_name: 'p_subtype_books_magazines', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps125 = CategoryProductsubtype.create!(name: 'desk accessories & organiser', code_name: 'p_subtype_desk_accessories', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps126 = CategoryProductsubtype.create!(name: 'art supplies', code_name: 'p_subtype_art_supplies', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps127 = CategoryProductsubtype.create!(name: 'office binding supplies', code_name: 'p_subtype_office_binding', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps128 = CategoryProductsubtype.create!(name: 'filing products', code_name: 'p_subtype_filing_products', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps129 = CategoryProductsubtype.create!(name: 'calendars, planners & cards', code_name: 'p_subtype_calendars', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps130 = CategoryProductsubtype.create!(name: 'mail & shipping supplies', code_name: 'p_subtype_mail_shipping', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps131 = CategoryProductsubtype.create!(name: 'paper', code_name: 'p_subtype_paper', category_productitemtype_id: cpit13.id, user_id: us01.id)
cps132 = CategoryProductsubtype.create!(name: 'presentation supplies', code_name: 'p_subtype_presentation_supplies', category_productitemtype_id: cpit13.id, user_id: us01.id)
# security & protection
cps133 = CategoryProductsubtype.create!(name: 'security alarm & sensors', code_name: 'p_subtype_security', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps134 = CategoryProductsubtype.create!(name: 'smart card system', code_name: 'p_subtype_smart_card', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps135 = CategoryProductsubtype.create!(name: 'door intercom system', code_name: 'p_subtype_door_intercom', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps136 = CategoryProductsubtype.create!(name: 'workplace safety supplies', code_name: 'p_subtype_workplace_safety', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps137 = CategoryProductsubtype.create!(name: 'fire protection', code_name: 'p_subtype_fire_protection', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps138 = CategoryProductsubtype.create!(name: 'video surveillance', code_name: 'p_subtype_video_surveillance', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps139 = CategoryProductsubtype.create!(name: 'self defense supplies', code_name: 'p_subtype_defense_supplies', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps140 = CategoryProductsubtype.create!(name: 'access control systems', code_name: 'p_subtype_access_control_system', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps141 = CategoryProductsubtype.create!(name: 'roadway safety', code_name: 'p_subtype_roadway_safety', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps142 = CategoryProductsubtype.create!(name: 'transmission & cables', code_name: 'p_subtype_transmission_cables', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps143 = CategoryProductsubtype.create!(name: 'IoT devices', code_name: 'p_subtype_IoT_devices', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps144 = CategoryProductsubtype.create!(name: 'security inspection device', code_name: 'p_subtype_security_inspection_device', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps145 = CategoryProductsubtype.create!(name: 'lightning protection', code_name: 'p_subtype_lightning_protection', category_productitemtype_id: cpit14.id, user_id: us01.id)
cps146 = CategoryProductsubtype.create!(name: 'emergency kits', code_name: 'p_subtype_emergency_kits', category_productitemtype_id: cpit14.id, user_id: us01.id)
# consumer electronics
cps147 = CategoryProductsubtype.create!(name: 'VR/AR devices', code_name: 'p_subtype_paper_vr_ar_devices', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps148 = CategoryProductsubtype.create!(name: 'speakers', code_name: 'p_subtype_speakers', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps149 = CategoryProductsubtype.create!(name: 'earphones & headphones', code_name: 'p_subtype_earphones', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps150 = CategoryProductsubtype.create!(name: 'home electronic accessories', code_name: 'p_subtype_home_electronic', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps151 = CategoryProductsubtype.create!(name: 'power source', code_name: 'p_subtype_power_source', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps152 = CategoryProductsubtype.create!(name: 'live equipment', code_name: 'p_subtype_live_equipment', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps153 = CategoryProductsubtype.create!(name: 'HIFI devices', code_name: 'p_subtype_hifi', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps154 = CategoryProductsubtype.create!(name: 'robot', code_name: 'p_subtype_robot', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps155 = CategoryProductsubtype.create!(name: 'wearable devices', code_name: 'p_subtype_wearable', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps156 = CategoryProductsubtype.create!(name: 'video games', code_name: 'p_subtype_video_games', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps157 = CategoryProductsubtype.create!(name: 'camera & photo', code_name: 'p_subtype_camera_photo', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps158 = CategoryProductsubtype.create!(name: 'accessories & parts', code_name: 'p_subtype_accessories_part', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps159 = CategoryProductsubtype.create!(name: 'audio & video', code_name: 'p_subtype_audio_video', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps160 = CategoryProductsubtype.create!(name: 'electronic cigarettes', code_name: 'p_subtype_electronic_cigarettes', category_productitemtype_id: cpit15.id, user_id: us01.id)
cps161 = CategoryProductsubtype.create!(name: 'smart remote control', code_name: 'p_subtype_smart_remote_control', category_productitemtype_id: cpit15.id, user_id: us01.id)
# pet supplies
cps162 = CategoryProductsubtype.create!(name: 'training aids', code_name: 'p_subtype_training_aids', category_productitemtype_id: cpit16.id, user_id: us01.id)
cps163 = CategoryProductsubtype.create!(name: 'pet trackers', code_name: 'p_subtype_pet_trackers', category_productitemtype_id: cpit16.id, user_id: us01.id)
cps164 = CategoryProductsubtype.create!(name: 'litter & housebreaking', code_name: 'p_subtype_litter', category_productitemtype_id: cpit16.id, user_id: us01.id)
cps165 = CategoryProductsubtype.create!(name: 'collars & leads', code_name: 'p_subtype_collars', category_productitemtype_id: cpit16.id, user_id: us01.id)
cps166 = CategoryProductsubtype.create!(name: 'pet health care & hygiene', code_name: 'p_subtype_pet_health_care', category_productitemtype_id: cpit16.id, user_id: us01.id)
cps167 = CategoryProductsubtype.create!(name: 'pet habitat, housing & furniture', code_name: 'p_subtype_pet_habitat', category_productitemtype_id: cpit16.id, user_id: us01.id)
cps168 = CategoryProductsubtype.create!(name: 'grooming & toys', code_name: 'p_subtype_grooming_toys', category_productitemtype_id: cpit16.id, user_id: us01.id)
cps169 = CategoryProductsubtype.create!(name: 'pet memorials', code_name: 'p_subtype_pet_memorials', category_productitemtype_id: cpit16.id, user_id: us01.id)
cps170 = CategoryProductsubtype.create!(name: 'pet food', code_name: 'p_subtype_pet_food', category_productitemtype_id: cpit16.id, user_id: us01.id)
cps171 = CategoryProductsubtype.create!(name: 'clothing, shoes & carriers', code_name: 'p_subtype_clothing', category_productitemtype_id: cpit16.id, user_id: us01.id)
cps172 = CategoryProductsubtype.create!(name: 'pet medical supplies', code_name: 'p_subtype_pet_medical_supplies', category_productitemtype_id: cpit16.id, user_id: us01.id)
# toys & hobbies
cps173 = CategoryProductsubtype.create!(name: 'stress relief toy', code_name: 'p_subtype_stress_relief_toy', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps174 = CategoryProductsubtype.create!(name: 'pools & water fun', code_name: 'p_subtype_pools_water', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps175 = CategoryProductsubtype.create!(name: 'stuffed animals & plush', code_name: 'p_subtype_stuffed_animals', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps176 = CategoryProductsubtype.create!(name: 'arts & crafts, DIY toys', code_name: 'p_subtype_arts_crafts', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps177 = CategoryProductsubtype.create!(name: 'high tech toys', code_name: 'p_subtype_high_tech_toys', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps178 = CategoryProductsubtype.create!(name: 'building construction toys', code_name: 'p_subtype_construction_toys', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps179 = CategoryProductsubtype.create!(name: 'action & toy figures', code_name: 'p_subtype_action_toy', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps180 = CategoryProductsubtype.create!(name: 'puzzles & games', code_name: 'p_subtype_puzzles_games', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps181 = CategoryProductsubtype.create!(name: 'dolls & accessories', code_name: 'p_subtype_dolls_accessories', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps182 = CategoryProductsubtype.create!(name: 'novelty & gag toys', code_name: 'p_subtype_novelty', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps183 = CategoryProductsubtype.create!(name: 'model building', code_name: 'p_subtype_model_building', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps184 = CategoryProductsubtype.create!(name: 'remote control toy', code_name: 'p_subtype_remote_control_toy', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps185 = CategoryProductsubtype.create!(name: 'baby & toddler toys', code_name: 'p_subtype_toddler_toys', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps186 = CategoryProductsubtype.create!(name: 'pretend play', code_name: 'p_subtype_pretend_play', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps187 = CategoryProductsubtype.create!(name: 'outdoor fun & sports', code_name: 'p_subtype_outdoor_fun_sports', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps188 = CategoryProductsubtype.create!(name: 'electronic toys', code_name: 'p_subtype_electronic_toys', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps189 = CategoryProductsubtype.create!(name: 'classic toys', code_name: 'p_subtype_classic_toys', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps190 = CategoryProductsubtype.create!(name: 'learning & education', code_name: 'p_subtype_learning_education', category_productitemtype_id: cpit17.id, user_id: us01.id)
cps191 = CategoryProductsubtype.create!(name: 'board games', code_name: 'p_subtype_board_games', category_productitemtype_id: cpit17.id, user_id: us01.id)
# musical instruments
cps192 = CategoryProductsubtype.create!(name: 'guitar', code_name: 'p_subtype_guitar', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps193 = CategoryProductsubtype.create!(name: 'violin', code_name: 'p_subtype_violin', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps194 = CategoryProductsubtype.create!(name: 'drum', code_name: 'p_subtype_drum', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps195 = CategoryProductsubtype.create!(name: 'ukulele', code_name: 'p_subtype_ukulele', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps196 = CategoryProductsubtype.create!(name: 'cello', code_name: 'p_subtype_cello', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps197 = CategoryProductsubtype.create!(name: 'guzheng', code_name: 'p_subtype_guzheng', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps198 = CategoryProductsubtype.create!(name: 'harp', code_name: 'p_subtype_harp', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps199 = CategoryProductsubtype.create!(name: 'urheen', code_name: 'p_subtype_urheen', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps200 = CategoryProductsubtype.create!(name: 'viola', code_name: 'p_subtype_viola', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps201 = CategoryProductsubtype.create!(name: 'mandolin', code_name: 'p_subtype_mandolin', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps202 = CategoryProductsubtype.create!(name: 'harmonica', code_name: 'p_subtype_harmonica', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps203 = CategoryProductsubtype.create!(name: 'saxophone', code_name: 'p_subtype_saxophone', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps204 = CategoryProductsubtype.create!(name: 'flute', code_name: 'p_subtype_flute', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps205 = CategoryProductsubtype.create!(name: 'clarinet', code_name: 'p_subtype_clarinet', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps206 = CategoryProductsubtype.create!(name: 'piccolo', code_name: 'p_subtype_piccolo', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps207 = CategoryProductsubtype.create!(name: 'recorder', code_name: 'p_subtype_recorder', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps208 = CategoryProductsubtype.create!(name: 'oboe', code_name: 'p_subtype_oboe', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps209 = CategoryProductsubtype.create!(name: 'bells & chimes', code_name: 'p_subtype_bells', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps210 = CategoryProductsubtype.create!(name: 'gong & cymbals', code_name: 'p_subtype_gong', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps211 = CategoryProductsubtype.create!(name: 'trumpet', code_name: 'p_subtype_trumpet', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps212 = CategoryProductsubtype.create!(name: 'trombone', code_name: 'p_subtype_trombone', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps213 = CategoryProductsubtype.create!(name: 'baritone', code_name: 'p_subtype_baritone', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps214 = CategoryProductsubtype.create!(name: 'tuba', code_name: 'p_subtype_tuba', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps215 = CategoryProductsubtype.create!(name: 'mellophone', code_name: 'p_subtype_mellophone', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps216 = CategoryProductsubtype.create!(name: 'cornet', code_name: 'p_subtype_cornet', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps217 = CategoryProductsubtype.create!(name: 'euphonium', code_name: 'p_subtype_euphonium', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps218 = CategoryProductsubtype.create!(name: 'flugelhorn', code_name: 'p_subtype_flugelhorn', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps219 = CategoryProductsubtype.create!(name: 'piano', code_name: 'p_subtype_piano', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps220 = CategoryProductsubtype.create!(name: 'electric organ', code_name: 'p_subtype_electric_organ', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps221 = CategoryProductsubtype.create!(name: 'accordion', code_name: 'p_subtype_accordion', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps222 = CategoryProductsubtype.create!(name: 'ocarina', code_name: 'p_subtype_ocarina', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps223 = CategoryProductsubtype.create!(name: 'kazoo', code_name: 'p_subtype_kazoo', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps224 = CategoryProductsubtype.create!(name: 'maraca', code_name: 'p_subtype_maraca', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps225 = CategoryProductsubtype.create!(name: 'xylophone', code_name: 'p_subtype_xylophone', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps226 = CategoryProductsubtype.create!(name: 'crow sounder', code_name: 'p_subtype_crow_sounder', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps227 = CategoryProductsubtype.create!(name: 'stick shaker', code_name: 'p_subtype_stick_shaker', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps228 = CategoryProductsubtype.create!(name: 'castanets', code_name: 'p_subtype_castanets', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps229 = CategoryProductsubtype.create!(name: 'rainmaker shaker', code_name: 'p_subtype_rainmaker_shaker', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps230 = CategoryProductsubtype.create!(name: 'rhythm sticks', code_name: 'p_subtype_rhythm_sticks', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps231 = CategoryProductsubtype.create!(name: 'triangle', code_name: 'p_subtype_triangle', category_productitemtype_id: cpit18.id, user_id: us01.id)
cps232 = CategoryProductsubtype.create!(name: 'kokiriko', code_name: 'p_subtype_kokiriko', category_productitemtype_id: cpit18.id, user_id: us01.id)
# hair extensions & wigs
cps233 = CategoryProductsubtype.create!(name: 'human hair', code_name: 'p_subtype_human_hair', category_productitemtype_id: cpit19.id, user_id: us01.id)
cps234 = CategoryProductsubtype.create!(name: 'synthetic hair', code_name: 'p_subtype_synthetic_hair', category_productitemtype_id: cpit19.id, user_id: us01.id)
cps235 = CategoryProductsubtype.create!(name: 'hair supplies', code_name: 'p_subtype_hair_supplies', category_productitemtype_id: cpit19.id, user_id: us01.id)
# salon equipments
cps236 = CategoryProductsubtype.create!(name: 'salon furniture', code_name: 'p_subtype_salon_furniture', category_productitemtype_id: cpit20.id, user_id: us01.id)
cps237 = CategoryProductsubtype.create!(name: 'salon electrical equipments', code_name: 'p_subtype_salon_electrical_equipments', category_productitemtype_id: cpit20.id, user_id: us01.id)
cps238 = CategoryProductsubtype.create!(name: 'salon tools & supplies', code_name: 'p_subtype_salon_tools_supplies', category_productitemtype_id: cpit20.id, user_id: us01.id)
# automobiles & motorcycles
cps239 = CategoryProductsubtype.create!(name: 'car light', code_name: 'p_subtype_car_light', category_productitemtype_id: cpit21.id, user_id: us01.id)
cps240 = CategoryProductsubtype.create!(name: 'car repair tools', code_name: 'p_subtype_car_repair_tools', category_productitemtype_id: cpit21.id, user_id: us01.id)
cps241 = CategoryProductsubtype.create!(name: 'ATV, RV, Boat & other vehicles parts', code_name: 'p_subtype_vehicles_parts', category_productitemtype_id: cpit21.id, user_id: us01.id)
cps242 = CategoryProductsubtype.create!(name: 'travel & roadway product', code_name: 'p_subtype_travel_roadway_product', category_productitemtype_id: cpit21.id, user_id: us01.id)
cps243 = CategoryProductsubtype.create!(name: 'car wash & maintenance', code_name: 'p_subtype_car_wash_maintenance', category_productitemtype_id: cpit21.id, user_id: us01.id)
cps244 = CategoryProductsubtype.create!(name: 'motorcycle accessories & parts', code_name: 'p_subtype_motorcycle_part', category_productitemtype_id: cpit21.id, user_id: us01.id)
cps245 = CategoryProductsubtype.create!(name: 'car electronics', code_name: 'p_subtype_car_electronics', category_productitemtype_id: cpit21.id, user_id: us01.id)
cps246 = CategoryProductsubtype.create!(name: 'auto replacement parts', code_name: 'p_subtype_auto_replacement_parts', category_productitemtype_id: cpit21.id, user_id: us01.id)
cps247 = CategoryProductsubtype.create!(name: 'exterior accessories', code_name: 'p_subtype_exterior_accessories', category_productitemtype_id: cpit21.id, user_id: us01.id)
cps248 = CategoryProductsubtype.create!(name: 'interior accessories', code_name: 'p_subtype_interior_accessories', category_productitemtype_id: cpit21.id, user_id: us01.id)
cps249 = CategoryProductsubtype.create!(name: 'vehicles & transportation', code_name: 'p_subtype_vehicles_transportation', category_productitemtype_id: cpit21.id, user_id: us01.id)
# sport equipments
cps250 = CategoryProductsubtype.create!(name: 'cycling', code_name: 'p_subtype_cycling', category_productitemtype_id: cpit22.id, user_id: us01.id)
cps251 = CategoryProductsubtype.create!(name: 'fitness & bodybuilding', code_name: 'p_subtype_fitness_bodybuilding', category_productitemtype_id: cpit22.id, user_id: us01.id)
cps252 = CategoryProductsubtype.create!(name: 'golf', code_name: 'p_subtype_golf', category_productitemtype_id: cpit22.id, user_id: us01.id)
cps253 = CategoryProductsubtype.create!(name: 'skiing & snowboarding', code_name: 'p_subtype_skiing_snowboarding', category_productitemtype_id: cpit22.id, user_id: us01.id)
cps254 = CategoryProductsubtype.create!(name: 'water sports', code_name: 'p_subtype_water_sports', category_productitemtype_id: cpit22.id, user_id: us01.id)
cps255 = CategoryProductsubtype.create!(name: 'hunting', code_name: 'p_subtype_hunting', category_productitemtype_id: cpit22.id, user_id: us01.id)
cps256 = CategoryProductsubtype.create!(name: 'fishing', code_name: 'p_subtype_fishing', category_productitemtype_id: cpit22.id, user_id: us01.id)
cps257 = CategoryProductsubtype.create!(name: 'camping & hiking', code_name: 'p_subtype_camping_hiking', category_productitemtype_id: cpit22.id, user_id: us01.id)
cps258 = CategoryProductsubtype.create!(name: 'racquet sports', code_name: 'p_subtype_racquet_sports', category_productitemtype_id: cpit22.id, user_id: us01.id)
# construction & real estate
cps259 = CategoryProductsubtype.create!(name: 'electrical equipments & supplies', code_name: 'p_subtype_electrical_equip_supplies', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps260 = CategoryProductsubtype.create!(name: 'construction materials', code_name: 'p_subtype_construction_materials', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps261 = CategoryProductsubtype.create!(name: 'hardware', code_name: 'p_subtype_hardware', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps262 = CategoryProductsubtype.create!(name: 'kitchen fixtures', code_name: 'p_subtype_kitchen_fixtures', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps263 = CategoryProductsubtype.create!(name: 'plumbing', code_name: 'p_subtype_plumbing', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps264 = CategoryProductsubtype.create!(name: 'painting supplies & wall treatments', code_name: 'p_subtype_painting_supplies', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps265 = CategoryProductsubtype.create!(name: 'family intelligence system', code_name: 'p_subtype_family_intelligence', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps266 = CategoryProductsubtype.create!(name: 'lights & lighting', code_name: 'p_subtype_lights', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps267 = CategoryProductsubtype.create!(name: 'doors, gates & windows', code_name: 'p_subtype_doors_fates_windows', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps268 = CategoryProductsubtype.create!(name: 'bathroom fixtures', code_name: 'p_subtype_bathroom_fixtures', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps269 = CategoryProductsubtype.create!(name: 'power electric tools', code_name: 'p_subtype_power_electric_tools', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps270 = CategoryProductsubtype.create!(name: 'welding & soldering supplies', code_name: 'p_subtype_welding_supplies', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps271 = CategoryProductsubtype.create!(name: 'insulation', code_name: 'p_subtype_insulation', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps272 = CategoryProductsubtype.create!(name: 'woodworking machinery & parts', code_name: 'p_subtype_woodworking_machinery ', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps273 = CategoryProductsubtype.create!(name: 'welding equipment', code_name: 'p_subtype_welding_equipment', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps274 = CategoryProductsubtype.create!(name: 'measurement & analysis tools', code_name: 'p_subtype_measurement_analysis_tools', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps275 = CategoryProductsubtype.create!(name: 'abrasives', code_name: 'p_subtype_abrasives', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps276 = CategoryProductsubtype.create!(name: 'abrasive tools', code_name: 'p_subtype_abrasives_tool', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps277 = CategoryProductsubtype.create!(name: 'riveter guns', code_name: 'p_subtype_riveter_guns', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps278 = CategoryProductsubtype.create!(name: 'hand & power tool accessories', code_name: 'p_subtype_hand_power_tool_accessories', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps279 = CategoryProductsubtype.create!(name: 'lifting tools & accessories', code_name: 'p_subtype_lifting_tools_accessories', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps280 = CategoryProductsubtype.create!(name: 'hand tools & parts', code_name: 'p_subtype_hand_tools_parts', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps281 = CategoryProductsubtype.create!(name: 'construction tools', code_name: 'p_subtype_construction_tools', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps282 = CategoryProductsubtype.create!(name: 'tool set', code_name: 'p_subtype_tool_set', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps283 = CategoryProductsubtype.create!(name: 'tool organisation', code_name: 'p_subtype_tool_organisation', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps284 = CategoryProductsubtype.create!(name: 'machine tools & accessories', code_name: 'p_subtype_machine_tools_accessories', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps285 = CategoryProductsubtype.create!(name: 'heating, venting & cooling', code_name: 'p_subtype_heating_venting_cooling', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps286 = CategoryProductsubtype.create!(name: 'prefabricated buildings', code_name: 'p_subtype_prefabricated_buildings', category_productitemtype_id: cpit23.id, user_id: us01.id)
cps297 = CategoryProductsubtype.create!(name: 'construction & building machinery', code_name: 'p_subtype_construction_building_machinery', category_productitemtype_id: cpit23.id, user_id: us01.id)


# level_04
CategoryProductstyle.delete_all
# accessories/belts
ccpst01 = CategoryProductstyle.create!(name: 'buckle', code_name: 'p_style_buckle', category_productsubtype_id: cps01.id, user_id: us01.id)
ccpst02 = CategoryProductstyle.create!(name: 'non buckle', code_name: 'p_style_non_buckle', category_productsubtype_id: cps01.id, user_id: us01.id)
# accessories/gloves
ccpst03 = CategoryProductstyle.create!(name: 'knitted', code_name: 'p_style_knitted', category_productsubtype_id: cps02.id, user_id: us01.id)
ccpst04 = CategoryProductstyle.create!(name: 'fingerless', code_name: 'p_style_fingerless', category_productsubtype_id: cps02.id, user_id: us01.id)
ccpst05 = CategoryProductstyle.create!(name: 'mitten', code_name: 'p_style_mitten', category_productsubtype_id: cps02.id, user_id: us01.id)
# accessories/hats & caps
ccpst06 = CategoryProductstyle.create!(name: 'hats', code_name: 'p_style_mitten', category_productsubtype_id: cps03.id, user_id: us01.id)
ccpst07 = CategoryProductstyle.create!(name: 'caps', code_name: 'p_style_caps', category_productsubtype_id: cps03.id, user_id: us01.id)
ccpst08 = CategoryProductstyle.create!(name: 'beanies', code_name: 'p_style_beanies', category_productsubtype_id: cps03.id, user_id: us01.id)
# accessories/hair accessories
ccpst09 = CategoryProductstyle.create!(name: 'headbands', code_name: 'p_style_headbands', category_productsubtype_id: cps04.id, user_id: us01.id)
ccpst10 = CategoryProductstyle.create!(name: 'hair clips', code_name: 'p_style_hair_clips', category_productsubtype_id: cps04.id, user_id: us01.id)
ccpst11 = CategoryProductstyle.create!(name: 'head scarves', code_name: 'p_style_head_scarves', category_productsubtype_id: cps04.id, user_id: us01.id)
ccpst12 = CategoryProductstyle.create!(name: 'hair extensions', code_name: 'p_style_hair_extensions', category_productsubtype_id: cps04.id, user_id: us01.id)
ccpst13 = CategoryProductstyle.create!(name: 'hair bands', code_name: 'p_style_hair_bands', category_productsubtype_id: cps04.id, user_id: us01.id)
ccpst14 = CategoryProductstyle.create!(name: 'hair ribbons', code_name: 'p_style_hair_ribbons', category_productsubtype_id: cps04.id, user_id: us01.id)
ccpst15 = CategoryProductstyle.create!(name: 'hair accessories', code_name: 'p_style_hair_accessories', category_productsubtype_id: cps04.id, user_id: us01.id)
ccpst16 = CategoryProductstyle.create!(name: 'fascinators', code_name: 'p_style_fascinators', category_productsubtype_id: cps04.id, user_id: us01.id)
ccpst17 = CategoryProductstyle.create!(name: 'hair jewelry', code_name: 'p_style_hair_jewelry', category_productsubtype_id: cps04.id, user_id: us01.id)
ccpst18 = CategoryProductstyle.create!(name: 'hair grips', code_name: 'p_style_hair_grips', category_productsubtype_id: cps04.id, user_id: us01.id)
# accessories/handbags & purses
ccpst19 = CategoryProductstyle.create!(name: 'waist bags', code_name: 'p_style_waist_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst20 = CategoryProductstyle.create!(name: 'shoulder bags', code_name: 'p_style_shoulder_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst21 = CategoryProductstyle.create!(name: 'briefcases', code_name: 'p_style__briefcases', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst22 = CategoryProductstyle.create!(name: 'crossbody bags', code_name: 'p_style_crossbody_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst23 = CategoryProductstyle.create!(name: 'money clippers', code_name: 'p_style_money_clippers', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst24 = CategoryProductstyle.create!(name: 'card & ID holders', code_name: 'p_style_card_id_holder', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst25 = CategoryProductstyle.create!(name: 'passport holders', code_name: 'p_style_passport_holders', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst26 = CategoryProductstyle.create!(name: 'coin purses', code_name: 'p_style_coin_purses', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst27 = CategoryProductstyle.create!(name: 'tote bags', code_name: 'p_style_tote_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst28 = CategoryProductstyle.create!(name: 'buckets', code_name: 'p_style_buckets', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst29 = CategoryProductstyle.create!(name: 'bumb bags', code_name: 'p_style_bum_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst30 = CategoryProductstyle.create!(name: 'backpacks', code_name: 'p_style_backpacks', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst31 = CategoryProductstyle.create!(name: 'cosmetic bags & cases', code_name: 'p_style_cosmetic_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst32 = CategoryProductstyle.create!(name: 'wallets', code_name: 'p_style_wallets', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst33 = CategoryProductstyle.create!(name: 'hobos', code_name: 'p_style_hobos', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst34 = CategoryProductstyle.create!(name: 'shopping bags', code_name: 'p_style_shopping_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst35 = CategoryProductstyle.create!(name: 'shoulder bags', code_name: 'p_style_shoulder_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst36 = CategoryProductstyle.create!(name: 'drawstring bags', code_name: 'p_style_drawstring_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst37 = CategoryProductstyle.create!(name: 'clutches', code_name: 'p_style_clutches', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst38 = CategoryProductstyle.create!(name: 'wristlets', code_name: 'p_style_wristlets', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst39 = CategoryProductstyle.create!(name: 'top-handle bags', code_name: 'p_style_top_handle_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst40 = CategoryProductstyle.create!(name: 'evening bags', code_name: 'p_style_evening_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst41 = CategoryProductstyle.create!(name: 'purses', code_name: 'p_style_purses', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst42 = CategoryProductstyle.create!(name: 'laptop cases', code_name: 'p_style_laptop_cases', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst43 = CategoryProductstyle.create!(name: 'school bags', code_name: 'p_style_school_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst44 = CategoryProductstyle.create!(name: 'luggages & travel bags', code_name: 'p_style_luggages', category_productsubtype_id: cps05.id, user_id: us01.id)
ccpst45 = CategoryProductstyle.create!(name: 'maternity bags', code_name: 'p_style_maternity_bags', category_productsubtype_id: cps05.id, user_id: us01.id)
# accessories/jewellery
ccpst46 = CategoryProductstyle.create!(name: 'earrings', code_name: 'p_style_earrings', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst47 = CategoryProductstyle.create!(name: 'necklace', code_name: 'p_style_necklace', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst48 = CategoryProductstyle.create!(name: 'bracelets', code_name: 'p_style_bracelets', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst49 = CategoryProductstyle.create!(name: 'rings', code_name: 'p_style_rings', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst50 = CategoryProductstyle.create!(name: 'chokers', code_name: 'p_style_chokers', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst51 = CategoryProductstyle.create!(name: 'anklets', code_name: 'p_style_anklets', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst52 = CategoryProductstyle.create!(name: 'bangles', code_name: 'p_style_bangles', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst53 = CategoryProductstyle.create!(name: 'ear cuffs', code_name: 'p_style_ear_cuffs', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst54 = CategoryProductstyle.create!(name: 'belly chains', code_name: 'p_style_belly_chains', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst55 = CategoryProductstyle.create!(name: 'jewellery packaging', code_name: 'p_style_jewellery_packaging', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst56 = CategoryProductstyle.create!(name: 'charms', code_name: 'p_style_charms', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst57 = CategoryProductstyle.create!(name: 'chains', code_name: 'p_style_chains', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst58 = CategoryProductstyle.create!(name: 'key chains', code_name: 'p_style_key_chains', category_productsubtype_id: cps06.id, user_id: us01.id)
ccpst59 = CategoryProductstyle.create!(name: 'brooches', code_name: 'p_style_brooches', category_productsubtype_id: cps06.id, user_id: us01.id)
# accessories/sunglasses
ccpst60 = CategoryProductstyle.create!(name: 'square', code_name: 'p_style_square', category_productsubtype_id: cps07.id, user_id: us01.id)
ccpst61 = CategoryProductstyle.create!(name: 'round', code_name: 'p_style_round', category_productsubtype_id: cps07.id, user_id: us01.id)
ccpst62 = CategoryProductstyle.create!(name: 'retro', code_name: 'p_style_retro', category_productsubtype_id: cps07.id, user_id: us01.id)
ccpst63 = CategoryProductstyle.create!(name: 'cat eye', code_name: 'p_style_cat_eye', category_productsubtype_id: cps07.id, user_id: us01.id)
ccpst64 = CategoryProductstyle.create!(name: 'aviator', code_name: 'p_style_aviator', category_productsubtype_id: cps07.id, user_id: us01.id)
ccpst65 = CategoryProductstyle.create!(name: 'flat brow', code_name: 'p_style_flat_brow', category_productsubtype_id: cps07.id, user_id: us01.id)
# accessories/scarves
ccpst66 = CategoryProductstyle.create!(name: 'knitted', code_name: 'p_style_knitted', category_productsubtype_id: cps08.id, user_id: us01.id)
ccpst67 = CategoryProductstyle.create!(name: 'non knitted', code_name: 'p_style_non_knitted', category_productsubtype_id: cps08.id, user_id: us01.id)
# accessories/umbrellas
ccpst68 = CategoryProductstyle.create!(name: 'straight', code_name: 'p_style_straight', category_productsubtype_id: cps09.id, user_id: us01.id)
ccpst69 = CategoryProductstyle.create!(name: 'folding', code_name: 'p_style_folding', category_productsubtype_id: cps09.id, user_id: us01.id)
# accessories/watches
ccpst70 = CategoryProductstyle.create!(name: 'digital', code_name: 'p_style_digital', category_productsubtype_id: cps10.id, user_id: us01.id)
ccpst71 = CategoryProductstyle.create!(name: 'battery powered', code_name: 'p_style_battery_powered', category_productsubtype_id: cps10.id, user_id: us01.id)
ccpst72 = CategoryProductstyle.create!(name: 'watch accessories', code_name: 'p_style_watch_accessories', category_productsubtype_id: cps10.id, user_id: us01.id)
# accessories/handkerchiefs
ccpst73 = CategoryProductstyle.create!(name: 'plain', code_name: 'p_style_plain', category_productsubtype_id: cps11.id, user_id: us01.id)
ccpst74 = CategoryProductstyle.create!(name: 'patterned', code_name: 'p_style_patterned', category_productsubtype_id: cps11.id, user_id: us01.id)
# accessories/ties & bow ties
ccpst75 = CategoryProductstyle.create!(name: 'ties', code_name: 'p_style_ties', category_productsubtype_id: cps12.id, user_id: us01.id)
ccpst76 = CategoryProductstyle.create!(name: 'bow ties', code_name: 'p_style_bow_ties', category_productsubtype_id: cps12.id, user_id: us01.id)
# --------------------------------------



















# products
Product.delete_all
pp01 = Product.create!(
  name:'cute bear baby knit hat',
  image: nil,
  image_url: "https://ae01.alicdn.com/kf/Se8fb6ef862ac432aa5b23fbb2bd5aab6L/Cute-Bear-Baby-Knit-Hat-Solid-Color-Soft-Comfortable-Toddler-Beanies-for-Boy-Girl-Cartoon-Autumn.jpg_.webp",
  description: "cute bear baby knit hat solid color soft comfortable toddler beanies for boy girl cartoon autumn winter warm kids knitted hat",
  user_id: us01.id,
  price: 0.2099e2,
  impressions_count: 0,
  category_producttype_id: cpt02.id,        #women
  category_productitemtype_id: cpit01.id,   #accessories
  category_productstyle_id: cpst05.id,      #hats & caps
  category_productsubtype_id: cps03.id,     #hats
  )